apiVersion: v1
kind: ConfigMap
metadata:
  name: kodify-backend-config
  labels:
    app: kodify-backend
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATABASE_URL: "postgresql://postgres:postgres@kodify-postgres:5432/kodify?schema=public"
  REDIS_HOST: "kodify-redis"
  REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodify-backend
  labels:
    app: kodify-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodify-backend
  template:
    metadata:
      labels:
        app: kodify-backend
    spec:
      containers:
        - name: backend
          image: kodify-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: kodify-backend-config
          readinessProbe:
            httpGet:
              path: "/api"
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/api"
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kodify-backend-service
  labels:
    app: kodify-backend
spec:
  type: ClusterIP
  selector:
    app: kodify-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
