apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kodify-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodify-postgres
  labels:
    app: kodify-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodify-postgres
  template:
    metadata:
      labels:
        app: kodify-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "kodify"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: kodify-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: kodify-postgres
  labels:
    app: kodify-postgres
spec:
  type: ClusterIP
  selector:
    app: kodify-postgres
  ports:
    - port: 5432
      targetPort: 5432
