apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodify-redis
  labels:
    app: kodify-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodify-redis
  template:
    metadata:
      labels:
        app: kodify-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          args:
            - redis-server
            - --save
            - ""
            - --appendonly
            - no
---
apiVersion: v1
kind: Service
metadata:
  name: kodify-redis
  labels:
    app: kodify-redis
spec:
  type: ClusterIP
  selector:
    app: kodify-redis
  ports:
    - port: 6379
      targetPort: 6379
