type QueryKeyId = string | number | null | undefined;

export const queryKeys = {
  subscriptions: {
    access: (userId: QueryKeyId, role: QueryKeyId) => ['subscriptions', 'access', userId, role] as const,
  },
  notifications: {
    mine: (userId: QueryKeyId, limit: QueryKeyId) => ['notifications', 'mine', userId, limit] as const,
  },
  finance: {
    dashboard: (userId: QueryKeyId, role: QueryKeyId) => ['finance', 'dashboard', userId, role] as const,
    dexPayRuntime: () => ['finance', 'dexpay-runtime'] as const,
    invoices: (userId: QueryKeyId) => ['finance', 'invoices', userId] as const,
  },
  account: {
    profile: (userId: QueryKeyId) => ['account', 'profile', userId] as const,
    security: (userId: QueryKeyId) => ['account', 'security', userId] as const,
  },
  messaging: {
    conversations: (userId: QueryKeyId, summaryOnly: boolean) => ['messaging', userId, summaryOnly ? 'summary' : 'full'] as const,
    directory: (userId: QueryKeyId) => ['messaging', 'directory', userId] as const,
  },
  apprenant: {
    root: (userId: QueryKeyId) => ['apprenant', userId] as const,
    enrollments: (userId: QueryKeyId) => [...queryKeys.apprenant.root(userId), 'enrollments'] as const,
    certificates: (userId: QueryKeyId) => [...queryKeys.apprenant.root(userId), 'certificates'] as const,
    progression: (userId: QueryKeyId) => [...queryKeys.apprenant.root(userId), 'progression'] as const,
    examens: (userId: QueryKeyId) => [...queryKeys.apprenant.root(userId), 'examens'] as const,
    examQuiz: (userId: QueryKeyId, examId: QueryKeyId) => [...queryKeys.apprenant.root(userId), 'exam-quiz', examId] as const,
    courseDetail: (userId: QueryKeyId, courseId: QueryKeyId) => [...queryKeys.apprenant.root(userId), 'course-detail', courseId] as const,
  },
  formateur: {
    root: (userId: QueryKeyId) => ['formateur', userId] as const,
    dashboard: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'dashboard'] as const,
    courses: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'courses'] as const,
    evaluations: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'evaluations'] as const,
    certificates: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'certificates'] as const,
    revenue: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'revenue'] as const,
    virtualClasses: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'virtual-classes'] as const,
    community: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'community'] as const,
    learners: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'learners'] as const,
    learnerDetail: (userId: QueryKeyId, studentId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'learner-detail', studentId] as const,
    publicProfile: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'public-profile'] as const,
    courseProgram: (userId: QueryKeyId, courseId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'course-program', courseId] as const,
    examQuiz: (userId: QueryKeyId, examId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'exam-quiz', examId] as const,
    analytics: (userId: QueryKeyId) => [...queryKeys.formateur.root(userId), 'analytics'] as const,
  },
  client: {
    root: (userId: QueryKeyId) => ['client', userId] as const,
    dashboard: (userId: QueryKeyId) => [...queryKeys.client.root(userId), 'dashboard'] as const,
    providers: (userId: QueryKeyId) => [...queryKeys.client.root(userId), 'providers'] as const,
    reservations: (userId: QueryKeyId) => [...queryKeys.client.root(userId), 'reservations'] as const,
    orders: (userId: QueryKeyId) => [...queryKeys.client.root(userId), 'orders'] as const,
  },
  prestataire: {
    root: (userId: QueryKeyId) => ['prestataire', userId] as const,
    dashboard: (userId: QueryKeyId) => [...queryKeys.prestataire.root(userId), 'dashboard'] as const,
    bookings: (userId: QueryKeyId) => [...queryKeys.prestataire.root(userId), 'bookings'] as const,
    reviews: (userId: QueryKeyId) => [...queryKeys.prestataire.root(userId), 'reviews'] as const,
    services: (userId: QueryKeyId) => [...queryKeys.prestataire.root(userId), 'services'] as const,
  },
  porteur: {
    root: (userId: QueryKeyId) => ['porteur', userId] as const,
    dashboard: (userId: QueryKeyId) => [...queryKeys.porteur.root(userId), 'dashboard'] as const,
    projects: (userId: QueryKeyId) => [...queryKeys.porteur.root(userId), 'projects'] as const,
    projectDetail: (userId: QueryKeyId, projectId: QueryKeyId) => [...queryKeys.porteur.root(userId), 'project-detail', projectId] as const,
    partnerships: (userId: QueryKeyId) => [...queryKeys.porteur.root(userId), 'partnerships'] as const,
    funding: (userId: QueryKeyId) => [...queryKeys.porteur.root(userId), 'funding'] as const,
    fundingDetail: (userId: QueryKeyId, roundId: QueryKeyId) => [...queryKeys.porteur.root(userId), 'funding-detail', roundId] as const,
    publicProfileData: (userId: QueryKeyId) => [...queryKeys.porteur.root(userId), 'public-profile-data'] as const,
  },
  parent: {
    dashboard: (userId: QueryKeyId) => ['parent', 'dashboard', userId] as const,
  },
  admin: {
    analytics: (range: QueryKeyId) => ['admin', 'analytics', range] as const,
    content: () => ['admin', 'content'] as const,
    reports: () => ['admin', 'reports'] as const,
    security: () => ['admin', 'security'] as const,
    dashboard: (scope?: QueryKeyId) => ['admin', 'dashboard', scope] as const,
    operations: () => ['admin', 'operations'] as const,
    projectFunding: () => ['admin', 'project-funding'] as const,
    payments: (scope?: QueryKeyId) => ['admin', 'payments', scope] as const,
    users: (scope?: QueryKeyId) => ['admin', 'users', scope] as const,
    accreditations: () => ['admin', 'accreditations'] as const,
    settings: () => ['admin', 'settings'] as const,
    communications: () => ['admin', 'communications'] as const,
    communicationGateways: () => ['admin', 'communications', 'gateways'] as const,
    messages: () => ['admin', 'messages'] as const,
    messageDirectory: () => ['admin', 'messages', 'directory'] as const,
  },
  partenaire: {
    root: (userId: QueryKeyId) => ['partenaire', userId] as const,
    dashboard: (userId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'dashboard'] as const,
    opportunities: (userId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'opportunities'] as const,
    trackedProjects: (userId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'tracked-projects'] as const,
    trackedProjectDetail: (userId: QueryKeyId, projectId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'tracked-project-detail', projectId] as const,
    collaborations: (userId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'collaborations'] as const,
    fundingSimulation: (userId: QueryKeyId, projectId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'funding-simulation', projectId] as const,
    fundingCommitments: (userId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'funding-commitments'] as const,
    publicProfileData: (userId: QueryKeyId) => [...queryKeys.partenaire.root(userId), 'public-profile-data'] as const,
  },
};
