export const STORAGE_KEYS = {
  completed: (courseId: number) => `course-${courseId}-completed`,
  bookmarks: (courseId: number) => `course-${courseId}-bookmarks`,
  notes: (courseId: number) => `course-${courseId}-notes`,
  lastViewed: (courseId: number) => `course-${courseId}-last-viewed`,
  quizScores: (courseId: number) => `course-${courseId}-quiz-scores`,
  badges: () => `course-badges-unlocked`,
  courseHistory: () => `course-history`,
  xp: () => `learning-xp`,
  learningDays: () => `learning-days`,
  dailyXP: (date: string) => `daily-xp-${date}`,
  leaderboard: () => `leaderboard-entries`,
  certificates: () => `learning-certificates`,
  sessionTime: (courseId: number) => `course-${courseId}-session-time`,
  totalLearningTime: () => `total-learning-time-seconds`,
};

export interface QuizScore {
  date: string;
  score: number;
  total: number;
  answers: Record<number, number>;
}

export interface CourseHistoryEntry {
  courseId: number;
  title: string;
  category: string;
  thumbnail: string;
  instructor: string;
  totalLessons: number;
  completedLessons: number;
  progress: number;
  lastAccessed: string;
  badge?: string;
  certificateId?: string;
  certificateDate?: string;
}

export interface CertificateEntry {
  id: string;
  courseId: number;
  courseTitle: string;
  instructor: string;
  category: string;
  issueDate: string;
  grade: number;
  skills: string[];
  status: 'active' | 'expired' | 'pending';
  autoGenerated: boolean;
}

export interface Badge {
  id: string;
  icon: string;
  name: string;
  description: string;
  color: string;
}

export interface LeaderboardEntry {
  id: string;
  name: string;
  avatar: string;
  xp: number;
  streak: number;
  coursesCompleted: number;
  lessonsCompleted: number;
  isCurrentUser?: boolean;
}

export interface LearningDay {
  date: string;
  xp: number;
}

export const XP_REWARDS = {
  lessonComplete: 15,
  quizComplete: 25,
  quizPerfect: 50,
  readingComplete: 10,
  exerciseComplete: 30,
  courseComplete: 200,
  streakBonus: 10,
  dailyLogin: 5,
};

export const BADGES: Badge[] = [
  { id: 'starter', icon: 'ri-flashlight-line', name: 'Premier pas', description: 'Avoir complété au moins 1 leçon', color: 'amber' },
  { id: 'halfway', icon: 'ri-trophy-line', name: 'À mi-parcours', description: 'Atteindre 50% de progression dans un cours', color: 'teal' },
  { id: 'finisher', icon: 'ri-award-line', name: 'Terminateur', description: 'Compléter 100% d\'un cours', color: 'emerald' },
  { id: 'quiz-master', icon: 'ri-medal-line', name: 'Maître du Quiz', description: 'Obtenir 5/5 à un quiz', color: 'violet' },
  { id: 'note-taker', icon: 'ri-sticky-note-line', name: 'Chercheur', description: 'Prendre des notes sur 5 leçons différentes', color: 'sky' },
  { id: 'bookmarker', icon: 'ri-bookmark-3-line', name: 'Collectionneur', description: 'Ajouter 10 leçons aux favoris', color: 'rose' },
  { id: 'xp-1000', icon: 'ri-fire-line', name: 'Apprenti passionné', description: 'Atteindre 1000 XP', color: 'orange' },
  { id: 'xp-5000', icon: 'ri-vip-crown-line', name: 'Expert', description: 'Atteindre 5000 XP', color: 'amber' },
  { id: 'streak-7', icon: 'ri-calendar-check-line', name: 'Régularité', description: 'Apprendre 7 jours consécutifs', color: 'teal' },
  { id: 'streak-30', icon: 'ri-calendar-todo-line', name: 'Discipline', description: 'Apprendre 30 jours consécutifs', color: 'emerald' },
  { id: 'courses-5', icon: 'ri-stack-line', name: 'Polyglotte', description: 'Commencer 5 cours différents', color: 'sky' },
  { id: 'courses-3-done', icon: 'ri-star-line', name: 'Triple couronne', description: 'Terminer 3 cours à 100%', color: 'amber' },
];

export function loadCompletedLessons(courseId: number): Set<number> {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.completed(courseId));
    if (raw) return new Set(JSON.parse(raw));
  } catch { /* noop */ }
  return new Set();
}

export function saveCompletedLessons(courseId: number, completed: Set<number>): void {
  localStorage.setItem(STORAGE_KEYS.completed(courseId), JSON.stringify(Array.from(completed)));
}

export function loadBookmarks(courseId: number): Set<number> {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.bookmarks(courseId));
    if (raw) return new Set(JSON.parse(raw));
  } catch { /* noop */ }
  return new Set();
}

export function saveBookmarks(courseId: number, bookmarks: Set<number>): void {
  localStorage.setItem(STORAGE_KEYS.bookmarks(courseId), JSON.stringify(Array.from(bookmarks)));
}

export function loadNotes(courseId: number): Record<number, string> {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.notes(courseId));
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return {};
}

export function saveNotes(courseId: number, notes: Record<number, string>): void {
  localStorage.setItem(STORAGE_KEYS.notes(courseId), JSON.stringify(notes));
}

export function loadLastViewedLesson(courseId: number): number | null {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.lastViewed(courseId));
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return null;
}

export function saveLastViewedLesson(courseId: number, lessonId: number): void {
  localStorage.setItem(STORAGE_KEYS.lastViewed(courseId), JSON.stringify(lessonId));
}

export function loadQuizScores(courseId: number): QuizScore[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.quizScores(courseId));
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return [];
}

export function saveQuizScore(courseId: number, score: QuizScore): void {
  const existing = loadQuizScores(courseId);
  existing.push(score);
  localStorage.setItem(STORAGE_KEYS.quizScores(courseId), JSON.stringify(existing));
}

export function loadUnlockedBadges(): string[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.badges());
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return [];
}

export function saveUnlockedBadges(badges: string[]): void {
  localStorage.setItem(STORAGE_KEYS.badges(), JSON.stringify(badges));
}

export function unlockBadge(badgeId: string): boolean {
  const current = loadUnlockedBadges();
  if (!current.includes(badgeId)) {
    current.push(badgeId);
    saveUnlockedBadges(current);
    return true;
  }
  return false;
}

export function checkAndAwardBadges(
  courseId: number,
  completedLessons: Set<number>,
  bookmarkedLessons: Set<number>,
  notes: Record<number, string>,
  quizScore?: { score: number; total: number },
  totalCourseLessons?: number,
): string[] {
  const newlyUnlocked: string[] = [];
  const totalLessonsCount = completedLessons.size;
  const totalBookmarks = bookmarkedLessons.size;
  const totalNotes = Object.values(notes).filter((n) => n.trim()).length;

  if (totalLessonsCount >= 1 && unlockBadge('starter')) newlyUnlocked.push('starter');

  if (totalCourseLessons && totalLessonsCount >= Math.ceil(totalCourseLessons * 0.5)) {
    if (unlockBadge('halfway')) newlyUnlocked.push('halfway');
  }

  if (totalCourseLessons && totalLessonsCount >= totalCourseLessons) {
    if (unlockBadge('finisher')) newlyUnlocked.push('finisher');
  }

  if (quizScore && quizScore.score === quizScore.total && quizScore.total >= 3) {
    if (unlockBadge('quiz-master')) newlyUnlocked.push('quiz-master');
  }
  if (totalNotes >= 5) {
    if (unlockBadge('note-taker')) newlyUnlocked.push('note-taker');
  }
  if (totalBookmarks >= 10) {
    if (unlockBadge('bookmarker')) newlyUnlocked.push('bookmarker');
  }

  // XP-based badges
  const xp = loadXP();
  if (xp >= 1000 && unlockBadge('xp-1000')) newlyUnlocked.push('xp-1000');
  if (xp >= 5000 && unlockBadge('xp-5000')) newlyUnlocked.push('xp-5000');

  // Streak badges
  const streak = getCurrentStreak();
  if (streak >= 7 && unlockBadge('streak-7')) newlyUnlocked.push('streak-7');
  if (streak >= 30 && unlockBadge('streak-30')) newlyUnlocked.push('streak-30');

  // Course diversity
  const history = loadCourseHistory();
  if (history.length >= 5 && unlockBadge('courses-5')) newlyUnlocked.push('courses-5');
  const completedCourses = history.filter((h) => h.progress === 100).length;
  if (completedCourses >= 3 && unlockBadge('courses-3-done')) newlyUnlocked.push('courses-3-done');

  return newlyUnlocked;
}

// XP System
export function loadXP(): number {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.xp());
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return 0;
}

export function saveXP(xp: number): void {
  localStorage.setItem(STORAGE_KEYS.xp(), JSON.stringify(Math.max(0, xp)));
}

export function addXP(amount: number): number {
  const current = loadXP();
  const next = current + amount;
  saveXP(next);
  // Track daily XP
  const today = new Date().toISOString().split('T')[0];
  const daily = loadDailyXP(today);
  saveDailyXP(today, daily + amount);
  // Track learning day
  trackLearningDay(today);
  return next;
}

export function loadDailyXP(date: string): number {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.dailyXP(date));
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return 0;
}

export function saveDailyXP(date: string, xp: number): void {
  localStorage.setItem(STORAGE_KEYS.dailyXP(date), JSON.stringify(Math.max(0, xp)));
}

export function trackLearningDay(date: string): void {
  const days = loadLearningDays();
  if (!days.includes(date)) {
    days.push(date);
    days.sort();
    localStorage.setItem(STORAGE_KEYS.learningDays(), JSON.stringify(days));
  }
}

export function loadLearningDays(): string[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.learningDays());
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return [];
}

export function getCurrentStreak(): number {
  const days = loadLearningDays();
  if (days.length === 0) return 0;
  const sorted = [...days].sort();
  let streak = 0;
  const today = new Date().toISOString().split('T')[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
  if (!sorted.includes(today) && !sorted.includes(yesterday)) return 0;

  for (let i = sorted.length - 1; i >= 0; i--) {
    const d = sorted[i];
    if (d === today || d === yesterday) {
      streak = 1;
      let check = new Date(d + 'T00:00:00');
      for (let j = i - 1; j >= 0; j--) {
        const prev = new Date(sorted[j] + 'T00:00:00');
        const diff = Math.round((check.getTime() - prev.getTime()) / 86400000);
        if (diff === 1) {
          streak++;
          check = prev;
        } else {
          break;
        }
      }
      break;
    }
  }
  return streak;
}

export function getLearningDaysForHeatmap(daysBack = 84): Record<string, number> {
  const days = loadLearningDays();
  const dailyXP: Record<string, number> = {};
  const today = new Date();
  for (let i = 0; i < daysBack; i++) {
    const d = new Date(today);
    d.setDate(d.getDate() - i);
    const ds = d.toISOString().split('T')[0];
    if (days.includes(ds)) {
      dailyXP[ds] = loadDailyXP(ds);
    }
  }
  return dailyXP;
}

// Leaderboard
export function loadLeaderboard(): LeaderboardEntry[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.leaderboard());
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  // Seed demo data
  const demo: LeaderboardEntry[] = [
    { id: 'user-1', name: 'Ibrahim Touré', avatar: 'https://readdy.ai/api/search-image?query=young%20african%20man%20student%20casual%20portrait%20smiling%20confident%20university%20campus%20background&width=40&height=40&seq=app-lb-ibrahim&orientation=squarish', xp: 3240, streak: 12, coursesCompleted: 2, lessonsCompleted: 45 },
    { id: 'user-2', name: 'Fatou Sow', avatar: 'https://readdy.ai/api/search-image?query=african%20woman%20student%20professional%20portrait%20confident%20smile%20modern%20classroom%20background&width=40&height=40&seq=app-lb-fatou&orientation=squarish', xp: 2890, streak: 8, coursesCompleted: 1, lessonsCompleted: 38 },
    { id: 'user-3', name: 'Jean Mbarga', avatar: 'https://readdy.ai/api/search-image?query=african%20businessman%20professional%20portrait%20suit%20modern%20office%20confident%20smile&width=40&height=40&seq=app-lb-jean&orientation=squarish', xp: 2560, streak: 5, coursesCompleted: 1, lessonsCompleted: 34 },
    { id: 'user-4', name: 'Mamadou Seck', avatar: 'https://readdy.ai/api/search-image?query=african%20male%20software%20developer%20programmer%20working%20on%20laptop%20professional%20tech%20portrait%20modern%20office&width=40&height=40&seq=app-lb-mamadou&orientation=squarish', xp: 1980, streak: 3, coursesCompleted: 0, lessonsCompleted: 28 },
    { id: 'user-5', name: 'Khadija Mbaye', avatar: 'https://readdy.ai/api/search-image?query=professional%20african%20female%20student%20portrait%20clean%20white%20background%20happy%20smile%20casual%20attire&width=40&height=40&seq=app-lb-khadija&orientation=squarish', xp: 1650, streak: 2, coursesCompleted: 0, lessonsCompleted: 22 },
    { id: 'user-6', name: 'Sophie Nkomo', avatar: 'https://readdy.ai/api/search-image?query=african%20woman%20professional%20portrait%20modern%20office%20friendly%20confident&width=40&height=40&seq=app-lb-sophie&orientation=squarish', xp: 1340, streak: 4, coursesCompleted: 0, lessonsCompleted: 18 },
    { id: 'user-7', name: 'David Kouassi', avatar: 'https://readdy.ai/api/search-image?query=african%20man%20young%20professional%20portrait%20modern%20office%20friendly%20confident&width=40&height=40&seq=app-lb-david&orientation=squarish', xp: 980, streak: 1, coursesCompleted: 0, lessonsCompleted: 14 },
    { id: 'user-8', name: 'Aminata Diop', avatar: 'https://readdy.ai/api/search-image?query=professional%20african%20woman%20entrepreneur%20elegant%20portrait%20modern%20office%20confident&width=40&height=40&seq=app-lb-aminata&orientation=squarish', xp: 720, streak: 0, coursesCompleted: 0, lessonsCompleted: 10 },
    { id: 'user-9', name: 'Ousmane Ba', avatar: 'https://readdy.ai/api/search-image?query=professional%20african%20male%20entrepreneur%20portrait%20clean%20white%20background%20happy%20smile%20business%20casual&width=40&height=40&seq=app-lb-ousmane&orientation=squarish', xp: 450, streak: 1, coursesCompleted: 0, lessonsCompleted: 6 },
    { id: 'user-10', name: 'Aicha Fall', avatar: 'https://readdy.ai/api/search-image?query=professional%20african%20female%20young%20student%20portrait%20happy%20smile%20bright%20classroom%20background&width=40&height=40&seq=app-lb-aicha&orientation=squarish', xp: 210, streak: 0, coursesCompleted: 0, lessonsCompleted: 3 },
  ];
  localStorage.setItem(STORAGE_KEYS.leaderboard(), JSON.stringify(demo));
  return demo;
}

export function saveLeaderboard(entries: LeaderboardEntry[]): void {
  localStorage.setItem(STORAGE_KEYS.leaderboard(), JSON.stringify(entries));
}

export function updateLeaderboardUser(entry: LeaderboardEntry): void {
  const board = loadLeaderboard();
  const idx = board.findIndex((e) => e.id === entry.id);
  if (idx >= 0) {
    board[idx] = { ...board[idx], ...entry, isCurrentUser: true };
  } else {
    board.push({ ...entry, isCurrentUser: true });
  }
  board.sort((a, b) => b.xp - a.xp);
  saveLeaderboard(board);
}

export function getRank(): number {
  const board = loadLeaderboard();
  const me = board.find((e) => e.isCurrentUser);
  if (!me) return board.length + 1;
  return board.findIndex((e) => e.id === me.id) + 1;
}

export function loadCourseHistory(): CourseHistoryEntry[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.courseHistory());
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return [];
}

export function saveCourseHistory(history: CourseHistoryEntry[]): void {
  localStorage.setItem(STORAGE_KEYS.courseHistory(), JSON.stringify(history));
}

export function updateCourseHistory(entry: CourseHistoryEntry): void {
  const history = loadCourseHistory();
  const idx = history.findIndex((h) => h.courseId === entry.courseId);
  if (idx >= 0) {
    history[idx] = entry;
  } else {
    history.push(entry);
  }
  saveCourseHistory(history);
}

export function resetCourseProgress(courseId: number): void {
  localStorage.removeItem(STORAGE_KEYS.completed(courseId));
  localStorage.removeItem(STORAGE_KEYS.bookmarks(courseId));
  localStorage.removeItem(STORAGE_KEYS.notes(courseId));
  localStorage.removeItem(STORAGE_KEYS.lastViewed(courseId));
  localStorage.removeItem(STORAGE_KEYS.quizScores(courseId));
}

export function loadCertificates(): CertificateEntry[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.certificates());
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return [];
}

export function saveCertificates(certs: CertificateEntry[]): void {
  localStorage.setItem(STORAGE_KEYS.certificates(), JSON.stringify(certs));
}

export function addCertificate(cert: CertificateEntry): void {
  const certs = loadCertificates();
  if (!certs.find((c) => c.id === cert.id)) {
    certs.unshift(cert);
    saveCertificates(certs);
  }
}

export function generateCertificateId(courseId: number): string {
  const year = new Date().getFullYear();
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `C2P-${year}-${courseId}-${random}`;
}

export function getCourseCertificate(courseId: number): CertificateEntry | undefined {
  return loadCertificates().find((c) => c.courseId === courseId);
}

export function hasCertificate(courseId: number): boolean {
  return loadCertificates().some((c) => c.courseId === courseId);
}

// Session time tracking
export function loadSessionTime(courseId: number): number {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.sessionTime(courseId));
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return 0;
}

export function saveSessionTime(courseId: number, seconds: number): void {
  localStorage.setItem(STORAGE_KEYS.sessionTime(courseId), JSON.stringify(Math.max(0, seconds)));
}

export function addSessionTime(courseId: number, seconds: number): number {
  const current = loadSessionTime(courseId);
  const next = current + seconds;
  saveSessionTime(courseId, next);
  // Also add to total learning time
  const total = loadTotalLearningTime();
  saveTotalLearningTime(total + seconds);
  return next;
}

export function loadTotalLearningTime(): number {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.totalLearningTime());
    if (raw) return JSON.parse(raw);
  } catch { /* noop */ }
  return 0;
}

export function saveTotalLearningTime(seconds: number): void {
  localStorage.setItem(STORAGE_KEYS.totalLearningTime(), JSON.stringify(Math.max(0, seconds)));
}

export function formatLearningTime(totalSeconds: number): string {
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  if (hours > 0) return `${hours}h ${minutes}min`;
  return `${minutes}min`;
}

export function getCourseLearningTime(courseId: number): number {
  return loadSessionTime(courseId);
}

export function getAllCoursesLearningTime(): Record<number, number> {
  const result: Record<number, number> = {};
  const history = loadCourseHistory();
  for (const entry of history) {
    const seconds = loadSessionTime(entry.courseId);
    if (seconds > 0) result[entry.courseId] = seconds;
  }
  return result;
}
