import { z } from 'zod';

export const configValidationSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.string().default('3000'),
  DATABASE_URL: z.string().url(),
  APP_ORIGINS: z.string().default('http://localhost:3000,http://127.0.0.1:3000'),
  COOKIE_DOMAIN: z.string().optional(),
  COOKIE_SECURE: z.enum(['true', 'false']).default('false'),
  TRUST_PROXY: z.enum(['true', 'false']).default('false'),
  ACCESS_TOKEN_TTL_MINUTES: z.string().default('15'),
  REFRESH_TOKEN_TTL_DAYS: z.string().default('14'),
  SESSION_ABSOLUTE_TIMEOUT_HOURS: z.string().default('12'),
  LOGIN_RATE_LIMIT_MAX: z.string().default('30'),
  GLOBAL_RATE_LIMIT_MAX: z.string().default('180'),
  CSRF_COOKIE_NAME: z.string().default('c2p_csrf'),
  SESSION_COOKIE_NAME: z.string().default('c2p_at'),
  REFRESH_COOKIE_NAME: z.string().default('c2p_rt'),
  FRONTEND_MONITORING_ENABLED: z.enum(['true', 'false']).default('true'),
  REDIS_HOST: z.string().default('redis'),
  REDIS_PORT: z.string().default('6379'),
  REDIS_DISABLED: z.enum(['true', 'false']).default('false'),
  REDIS_USERNAME: z.string().optional(),
  REDIS_PASSWORD: z.string().optional(),
  REDIS_DB: z.string().default('0'),
  REDIS_TLS: z.enum(['true', 'false']).default('false'),
  SMS_PROVIDER: z.enum(['disabled', 'mock', 'sendtext']).default('mock'),
  SMS_SENDER_ID: z.string().optional(),
  SMS_TEST_RECIPIENT: z.string().optional(),
  SENDTEXT_BASE_URL: z.string().url().optional(),
  SENDTEXT_SEND_PATH: z.string().optional(),
  SENDTEXT_API_KEY: z.string().optional(),
  SENDTEXT_API_SECRET: z.string().optional(),
  SENDTEXT_TIMEOUT_MS: z.string().default('10000'),
  DEXPAY_ENABLED: z.enum(['true', 'false']).default('false'),
  DEXPAY_BASE_URL: z.string().url().optional(),
  DEXPAY_API_KEY: z.string().optional(),
  DEXPAY_API_SECRET: z.string().optional(),
  DEXPAY_TIMEOUT_MS: z.string().default('12000'),
  DEXPAY_DEFAULT_ASSET: z.string().default('DUSD'),
  DEXPAY_DEFAULT_CHAIN: z.string().default('BSC'),
  DEXPAY_ONRAMP_TYPE: z.enum(['BUY', 'SELL']).default('BUY'),
  DEXPAY_OFFRAMP_TYPE: z.enum(['BUY', 'SELL']).default('SELL'),
});

export type EnvironmentVariables = z.infer<typeof configValidationSchema>;
